name: "Test this PR"
author: "Sarah Gibson"
description: |
  Copy a PR from a forked repo into a branch on the parent repo so that
  workflows that require secrets can be run
inputs:
  access_token:
    description: |
      A GitHub access token with enough permissions to write to the parent repo
    required: true
  repository:
    description: "The repository id in the form 'owner/project'"
    required: false
    default: ${{ github.repository }}
  pr_number:
    description: "The number of the Pull Request to be tested"
    required: false
    default: ${{ github.event.issue.number }}
runs:
  using: "docker"
  image: "docker://sgibson91/test-this-pr-action"
  args:
    - ${{ inputs.access_token }}
    - ${{ inputs.repository }}
    - ${{ inputs.pr_number }}
