name: CI Tests

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
  pull_request:
    branches:
      - main

jobs:
  python-lint-format:
    uses:
      sgibson91/.github/.github/workflows/python-lint-format.yaml@main
