name: CI Tests

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tool: black
            args: --check
          - tool: flake8
            args: --ignore=E501

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r dev-requirements.txt

      - name: Run ${{ matrix.tool }}
        run: |
          ${{ matrix.tool }} ${{ matrix.args }} src/
