name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  docker-build-push:
    uses: sgibson91/.github/.github/workflows/docker-build.yaml@main
    with:
      image_name: sgibson91/test-this-pr-action
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
