name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.repository }}:latest
