name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'dependabot') == false || contains(github.head_ref, 'pre-commit') == false
    environment: docker
    steps:
      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image and push if necessary
        uses: docker/build-push-action@v3.1.1
        with:
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ github.repository }}:latest
